<a href="https://colab.research.google.com/github/ricvazquez/ColabFiles/blob/main/S06_Actividad_01_NumPy_273509.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sesión 06 — Actividad calificable: NumPy y preparación de datos

# Actividad calificada — NumPy y preparación de datos

**Programación para Analítica Descriptiva y Predictiva**

Maestría en Inteligencia Artificial y Analítica de Datos — UACJ

---


**Nombre completo:**  
**Matrícula:**  

---

**Entrega:** individual, en este notebook de Google Colab (comparte el enlace con permiso de edición para el docente).
**Plazo:** 7 días naturales a partir de la publicación de esta actividad.
**Penalización por entrega tardía:** 5% por día, hasta 7 días; después de eso, la actividad no se recibe.
**Valor total:** 100 puntos.

### Herramientas permitidas

Esta actividad evalúa lo visto hasta la Sesión 6: expresiones regulares (`re`), comprensión de listas, `map()`, `lambda`, y NumPy. **No uses pandas ni scikit-learn** — todavía no se han visto en el curso, y su uso no sumará puntos aunque el resultado sea correcto.

### Cómo se evalúa

Cada ejercicio indica su valor en puntos. Se evalúa el resultado correcto **y** el uso apropiado de las herramientas indicadas en cada enunciado — una solución correcta que ignore la herramienta pedida (por ejemplo, usar un bucle `for` donde se pide `map()` o una operación vectorizada) no obtiene el puntaje completo. Comenta tu código donde el paso no sea evidente.

## Librerías

Ejecuta esta celda antes de empezar.

In [10]:
import re
import numpy as np

## Datos de partida

Una red de 4 estaciones meteorológicas registró temperatura y humedad durante 5 días. Los datos llegaron en un formato de texto crudo, como ocurre frecuentemente al recibir información de sensores o sistemas externos. Ejecuta la siguiente celda para cargar las lecturas — **no la modifiques**.

In [11]:
lecturas_crudas = [
    "EST-01 | Dia1 | Temp: 22.3C | Hum: 60%",
    "EST-01 | Dia2 | Temp: 19.8C | Hum: 64%",
    "EST-01 | Dia3 | Temp: 24.1C | Hum: 58%",
    "EST-01 | Dia4 | Temp: 26.5C | Hum: 55%",
    "EST-01 | Dia5 | Temp: 21.0C | Hum: 63%",
    "EST-02 | Dia1 | Temp: 24.0C | Hum: 70%",
    "EST-02 | Dia2 | Temp: 23.5C | Hum: 72%",
    "EST-02 | Dia3 | Temp: 27.2C | Hum: 65%",
    "EST-02 | Dia4 | Temp: 20.1C | Hum: 74%",
    "EST-02 | Dia5 | Temp: 22.8C | Hum: 69%",
    "EST-03 | Dia1 | Temp: 18.5C | Hum: 80%",
    "EST-03 | Dia2 | Temp: 19.2C | Hum: 78%",
    "EST-03 | Dia3 | Temp: 20.0C | Hum: 77%",
    "EST-03 | Dia4 | Temp: 21.5C | Hum: 75%",
    "EST-03 | Dia5 | Temp: 19.9C | Hum: 79%",
    "EST-04 | Dia1 | Temp: 27.8C | Hum: 50%",
    "EST-04 | Dia2 | Temp: 26.3C | Hum: 52%",
    "EST-04 | Dia3 | Temp: 25.9C | Hum: 53%",
    "EST-04 | Dia4 | Temp: 24.0C | Hum: 56%",
    "EST-04 | Dia5 | Temp: 28.1C | Hum: 49%",
]

print(len(lecturas_crudas), "lecturas cargadas")
print(lecturas_crudas[0])

20 lecturas cargadas
EST-01 | Dia1 | Temp: 22.3C | Hum: 60%


---

## Ejercicio 1 — Extracción con expresiones regulares (10 pts)

Usando `re` y comprensión de listas, extrae de cada cadena en `lecturas_crudas` el identificador de estación (por ejemplo `'EST-01'`) y el valor de temperatura como texto (por ejemplo `'22.3'`, sin la `C`). El resultado debe ser una lista de tuplas `(estacion, temperatura_texto)`, en el mismo orden que `lecturas_crudas`.

*Por qué importa: en la práctica, los datos casi nunca llegan ya estructurados — extraerlos de texto libre es el primer paso de cualquier pipeline de análisis.*

In [12]:
# Tu código aquí
# extraidos = [...]

# Utilizamos un for para recorres el arreglo y con un regex extraemos las cadenas que nos interesan
extraidos = []
for s in lecturas_crudas:
    estytemp = re.search(r"^(EST-\d+).*?Temp:\s*([0-9]+(?:\.[0-9]+)?)C", s)
    extraidos += [(estytemp.group(1), estytemp.group(2))]
print(extraidos)

[('EST-01', '22.3'), ('EST-01', '19.8'), ('EST-01', '24.1'), ('EST-01', '26.5'), ('EST-01', '21.0'), ('EST-02', '24.0'), ('EST-02', '23.5'), ('EST-02', '27.2'), ('EST-02', '20.1'), ('EST-02', '22.8'), ('EST-03', '18.5'), ('EST-03', '19.2'), ('EST-03', '20.0'), ('EST-03', '21.5'), ('EST-03', '19.9'), ('EST-04', '27.8'), ('EST-04', '26.3'), ('EST-04', '25.9'), ('EST-04', '24.0'), ('EST-04', '28.1')]


---

## Ejercicio 2 — Construcción del arreglo numérico (10 pts)

A partir de las temperaturas extraídas en el Ejercicio 1 (que están en texto), usa `map()` junto con una conversión a `float` para construir un `ndarray` de tipo numérico. Verifica e imprime su `dtype`.

*Por qué importa: conectar la extracción de texto con un tipo de dato numérico utilizable es un paso que se repite constantemente al preparar datos.*

In [13]:
# Tu código aquí
# temperaturas = np.array(...)

#Con ayuda de lo visto en clase lsit y map, extraemos las temperaturas y la convertimos a float
temps_orig = list(map(lambda x: x[1], extraidos))
print(type(temps_orig[0]))
temperaturas = np.array(list(map(lambda x: float(x[1]), extraidos)))
print(temperaturas.dtype)

<class 'str'>
float64


---

## Ejercicio 3 — Organización en una matriz 2D (10 pts)

Reorganiza el arreglo de temperaturas del Ejercicio 2 en una matriz de 4 filas (una por estación) × 5 columnas (una por día) usando `reshape()`. Los datos ya están ordenados por estación en `lecturas_crudas`, así que no necesitas reordenarlos manualmente. Reporta `shape`, `ndim`, `size` y `dtype` de la matriz resultante.

In [14]:
# Tu código aquí
# matriz_temp = temperaturas.reshape(...)

# Extraemos los datos solicitados de la matriz
matriz_temp = temperaturas.reshape(4, 5)
print(matriz_temp)
print(matriz_temp.shape)
print(matriz_temp.ndim)
print(matriz_temp.size)
print(matriz_temp.dtype)

[[22.3 19.8 24.1 26.5 21. ]
 [24.  23.5 27.2 20.1 22.8]
 [18.5 19.2 20.  21.5 19.9]
 [27.8 26.3 25.9 24.  28.1]]
(4, 5)
2
20
float64


---

## Ejercicio 4 — Indexado, slicing y transposición (10 pts)

A partir de `matriz_temp`:

1. Extrae la fila completa correspondiente a `EST-03`.
2. Extrae la columna completa correspondiente al Día 4.
3. Extrae la submatriz de las primeras 2 estaciones durante los primeros 3 días.
4. Transpón la matriz con `.T` e imprime su nueva forma (`shape`). En una celda de texto (Markdown) o un comentario, explica en qué situación tendría sentido trabajar con los días como filas y las estaciones como columnas.

In [15]:
# Tu código aquí

#gracias al acomodoo de la matriz relamente solo necesitamos indicar que rango de la matriz queremos extraer para cada punto
fila3 = matriz_temp[2]
col4 = matriz_temp[:, 3]
submatriz = matriz_temp[:2, :3]
tras = matriz_temp.T
print('Punto 1', fila3)
print('Punto 2', col4)
print('Punto 3', submatriz)
print('Punto 4', tras)
print('Punto 4.2', tras.shape)

Punto 1 [18.5 19.2 20.  21.5 19.9]
Punto 2 [26.5 20.1 21.5 24. ]
Punto 3 [[22.3 19.8 24.1]
 [24.  23.5 27.2]]
Punto 4 [[22.3 24.  18.5 27.8]
 [19.8 23.5 19.2 26.3]
 [24.1 27.2 20.  25.9]
 [26.5 20.1 21.5 24. ]
 [21.  22.8 19.9 28.1]]
Punto 4.2 (5, 4)


---

## Ejercicio 5 — Máscaras booleanas, verificación y fancy indexing (15 pts)

1. Usa una máscara booleana sobre `matriz_temp` para identificar qué lecturas superan los 25°C.
2. Usando `any()`, verifica si **alguna** estación tuvo, en algún día, una lectura mayor a 25°C.
3. Usando `all()`, verifica si la estación `EST-04` (fila correspondiente) tuvo **todos** sus días por encima de los 24°C.
4. Usando fancy indexing, reordena las filas de `matriz_temp` según la lista de prioridad `[2, 0, 3, 1]` (es decir, primero EST-03, luego EST-01, EST-04 y EST-02).

*Por qué importa: filtrar por condición, verificar rápidamente supuestos sobre los datos, y reordenar según un criterio externo son operaciones cotidianas al priorizar qué datos revisar primero.*

In [16]:
# Tu código aquí

#Usamos los for para sacar la informacion solicirada en cada punto
mb = [temp > 25 for temp in matriz_temp]
may = [any(temp) for temp in mb]
mb24 = [temp >24 for temp in matriz_temp[3]]
may24 = all(mb24)
fi = matriz_temp[[2, 0, 3, 1]]
print('Punto 1', mb)
print('Punto 2', may)
print('Punto 3', may24)
print('Punto 4', fi)

Punto 1 [array([False, False, False,  True, False]), array([False, False,  True, False, False]), array([False, False, False, False, False]), array([ True,  True,  True, False,  True])]
Punto 2 [True, True, False, True]
Punto 3 False
Punto 4 [[18.5 19.2 20.  21.5 19.9]
 [22.3 19.8 24.1 26.5 21. ]
 [27.8 26.3 25.9 24.  28.1]
 [24.  23.5 27.2 20.1 22.8]]


---

## Ejercicio 6 — Broadcasting y `np.where()` (15 pts)

Cada estación tiene un descalibre de sensor conocido, dado por este arreglo (en el mismo orden que las filas de `matriz_temp`: EST-01, EST-02, EST-03, EST-04):

```python
descalibre = np.array([-0.5, 1.2, 0.0, -1.0])
```

1. Usa broadcasting para aplicar la corrección correspondiente a cada fila de `matriz_temp` (cada estación se ajusta con su propio valor de `descalibre`). Guarda el resultado en una variable nueva, por ejemplo `matriz_corregida`. **Pista:** si intentas sumar `matriz_temp + descalibre` directamente obtendrás un error de formas incompatibles — el broadcasting solo funciona si `descalibre` tiene la forma `(4, 1)` en lugar de `(4,)`, para que cada valor se alinee con una fila completa. Usa `reshape()` (ya lo conoces del Bloque 2) para darle esa forma antes de sumar.
2. Sobre `matriz_corregida`, usa `np.where()` para generar una matriz paralela de etiquetas de texto: `'alta'` si la lectura corregida supera los 25°C, `'normal'` en caso contrario.

In [17]:
descalibre = np.array([-0.5, 1.2, 0.0, -1.0])

# Tu código aquí

#Le hacemos un resize a descalibre para poder sumarlo con la matriz temp y obtene le resultado
# Y en otra variable guardamos los valores de texto en la matriz
descalibre = descalibre.reshape((4, 1))
matriz_corregida = matriz_temp + descalibre
print(matriz_corregida)
matcor_alt = np.where(matriz_corregida > 25, 'alta', 'normal')
print(matcor_alt)

[[21.8 19.3 23.6 26.  20.5]
 [25.2 24.7 28.4 21.3 24. ]
 [18.5 19.2 20.  21.5 19.9]
 [26.8 25.3 24.9 23.  27.1]]
[['normal' 'normal' 'normal' 'alta' 'normal']
 ['alta' 'normal' 'alta' 'normal' 'normal']
 ['normal' 'normal' 'normal' 'normal' 'normal']
 ['alta' 'alta' 'normal' 'normal' 'alta']]


---

## Ejercicio 7 — Agregaciones por eje (15 pts)

Usando `matriz_corregida` del Ejercicio 6:

1. Calcula el promedio y la desviación estándar de temperatura **por estación** (usa el `axis` correspondiente).
2. Calcula el promedio de temperatura **por día** (usa el `axis` correspondiente).
3. Sin usar funciones no vistas en el curso (por ejemplo, sin `argmax`), determina **qué día** tuvo el promedio más alto entre estaciones. Sugerencia: obtén el valor máximo de los promedios por día con `.max()`, y compáralo con el arreglo de promedios por día usando `==` para generar una máscara booleana — la posición con `True` te dice qué día fue.

In [19]:
# Tu codigo aqui

#Gracias a axis le podemos decir que queremos que nos lo haga por filas
# Ya solo hacemos un for para recorrer el size del arreglo e imprmir la informacion solictada
prom_est = np.mean(matriz_corregida, axis=1)
desv_est = np.std(matriz_corregida, axis=1)
prom_dia = np.mean(matriz_corregida, axis=0)

for i in range(len(prom_est)):
    print('Estacion', i+1, 'Promedio:', round(prom_est[i], 2) ,'y desviacion:', round(desv_est[i], 2))
for i in range(len(prom_dia)):
    print('Dia', i+1, 'Promedio:', round(prom_dia[i], 2))

# Con pro max sacamos el maximo del dia
# despues recorremos el arreglo apra ver donde se encuentra el maximo
# Y con ayuda de index buscamos donde dio el true y le sumamos 1 para saber el dia
pro_max = np.max(prom_dia)
# dia = np.where(prom_dia == promax)
dia = [prom == pro_max for prom in prom_dia]
dia = dia.index(True)
print('Dia con el promedio mas alto', dia+1)

# print('Punto 3.- El dia ', dia[0][0]+1)
# print('Punto 3', prom_dia.argmax())

Estacion 1 Promedio: 22.24 y desviacion: 2.36
Estacion 2 Promedio: 24.72 y desviacion: 2.28
Estacion 3 Promedio: 19.82 y desviacion: 1.0
Estacion 4 Promedio: 25.42 y desviacion: 1.47
Dia 1 Promedio: 23.08
Dia 2 Promedio: 22.12
Dia 3 Promedio: 24.22
Dia 4 Promedio: 22.95
Dia 5 Promedio: 22.88
Dia con el promedio mas alto 3


---

## Ejercicio 8 — Síntesis: resumen por estación (15 pts)

Usando `map()` y/o comprensión de listas, genera una lista de cadenas de resumen, una por estación, que combine:

- El identificador de estación extraído en el Ejercicio 1.
- El promedio de temperatura corregida de esa estación (Ejercicio 7), formateado a un decimal.
- Su clasificación predominante (`'alta'` o `'normal'`) — usa `np.unique()` sobre las etiquetas de esa estación (del Ejercicio 6) para encontrar cuál aparece con mayor frecuencia entre las dos.

Formato esperado por cadena: `"EST-01: 23.4°C promedio — clasificación predominante: normal"`

Finalmente, ordena la lista de resúmenes de mayor a menor promedio de temperatura usando `sorted()` con `key` y `lambda` (como en la Sesión 4/5), e imprime el resultado ordenado.

In [ ]:
# Tu código aquí

#Primero extraje de la cadena de arriba cada estacion
resumen = []
resumen2 = []
listaf = []
for i, v in extraidos:
  if i not in resumen:
    resumen.append(i)

#Luego con unique y con el returns count saque cuantas veces aparece alta y normal en el arreglo
# lo compare una a una a ver cual numero era mas alto y le meti un try porque en columna solo habia normal entonces el otro numero no existia
pred = np.unique(matcor_alt[0], return_counts=True)
for i in matcor_alt:
  pred = np.unique(i, return_counts=True)
  try:
    if pred[1][0] > pred[1][1]:
      resumen2.append('alta')
    else:
      resumen2.append('normal')
  except:
    resumen2.append('normal')
resumen3 = [par for par in zip(resumen, prom_est,resumen2)]

# Saque los datos colectados y los pegue en una cadena como la que pide la practica

for i,v,c in resumen3:
  cf = i + ': ' + str(round(v, 1)) + '°C promedio — clasificación predominante: ' + c
  listaf.append(cf)
  # print(cf)

# Para el sorted tuve que hacer un doble split para separar el valor de temperaturade la cadena y del C
listaf = sorted(listaf, key=lambda x: float(x.split(":")[1].split("°C")[0].strip()), reverse=True)

for i in listaf:
  print(i)

# resumen = list(map(lambda x: x[0], resumen))
# print(resumen3)


---

## Antes de entregar

- Verifica que el notebook completo corra de principio a fin sin errores (**Entorno de ejecución → Ejecutar todas**).
- Confirma que no usaste pandas ni scikit-learn.
- Comparte el notebook con permiso de **edición** para el docente.
- Revisa que tu nombre y número de control estén en la primera celda.