<a href="https://colab.research.google.com/github/ricvazquez/ColabFiles/blob/main/S06_Actividad_02_ALGEBRALINEAL_273509.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Actividad calificada — Álgebra lineal con NumPy

**Programación para Analítica Descriptiva y Predictiva**
Maestría en Inteligencia Artificial y Analítica de Datos — UACJ

---

**Material de estudio previo:** `Material_Extra_Algebra_Lineal_NumPy.ipynb`. Revísalo antes de resolver esta actividad.

**Entrega:** individual, en este notebook de Google Colab (comparte el enlace con permiso de edición para el docente).
**Plazo:** 7 días naturales a partir de la publicación de esta actividad.
**Penalización por entrega tardía:** 5% por día, hasta 7 días; después de eso, la actividad no se recibe.
**Valor total:** 100 puntos.

### Herramientas permitidas

Esta actividad evalúa `np.linalg.norm()`, `np.dot()`/`@`, `np.linalg.det()`, `np.linalg.inv()`, `np.linalg.solve()`, y las operaciones de NumPy ya vistas en sesiones anteriores. No uses pandas ni scikit-learn.

### Cómo se evalúa

Cada ejercicio indica su valor en puntos. Se evalúa el resultado correcto **y** el uso de la función específica de `np.linalg` indicada en cada enunciado — calcular a mano una fórmula que NumPy ya resuelve (por ejemplo, programar la fórmula del determinante 2×2 en vez de usar `np.linalg.det()`) no obtiene el puntaje completo.

In [1]:
import numpy as np

## Parte 1 — Vectores: perfiles de producto

Una tienda en línea representa cada producto como un vector de 3 componentes: calificación de calidad, calificación de precio, y calificación de servicio (escala 1 a 5, donde 5 es mejor). Ejecuta la siguiente celda para cargar los tres productos — **no la modifiques**.

In [2]:
producto_A = np.array([4.5, 3.2, 5.0])
producto_B = np.array([4.0, 2.8, 4.7])
producto_C = np.array([1.0, 5.0, 1.2])

print(producto_A, producto_B, producto_C)

[4.5 3.2 5. ] [4.  2.8 4.7] [1.  5.  1.2]


---

### Ejercicio 1 — Norma de los vectores (10 pts)

Calcula la norma de `producto_A`, `producto_B` y `producto_C` usando `np.linalg.norm()`.

In [3]:
# Tu código aquí

# Con ayuda de np linalg norm sacamos la magnitud de cada vector
norma = np.linalg.norm(producto_A)
normb = np.linalg.norm(producto_B)
normc = np.linalg.norm(producto_C)
print('Norma A:',norma)
print('Norma B:',normb)
print('Norma C:',normc)

Norma A: 7.449161026585477
Norma B: 6.777167549942971
Norma C: 5.238320341483518


---

### Ejercicio 2 — Producto punto y ángulo (15 pts)

1. Calcula el producto punto entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`, usando `np.dot()` o `@`.
2. Calcula el ángulo (en grados) entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`.
3. Con base en los ángulos obtenidos, indica (en un comentario o celda de texto) cuál de los dos productos (`B` o `C`) es más similar a `producto_A`, y por qué el ángulo es el indicador correcto para esa comparación.

In [4]:
# Tu código aquí

#Con ayuda de las funciones de numpy calculamos el producto punto de a-b y a-c
prodpunab = np.dot(producto_A,producto_B)
prodpunac = np.dot(producto_A,producto_C)
print('Producto punto A-B:',prodpunab)
print('Producto punto A-C:',prodpunac)

# Con el producto punto, sacamos la similitud de coseno
# y de ahi los angulos
cosab = prodpunab/(norma*normb)
cosac = prodpunac/(norma*normc)
radab = np.arccos(cosab)
radac = np.arccos(cosac)
gradosab = np.degrees(radab)
gradosac = np.degrees(radac)
print('Angulo entre A-B:',round(gradosab,2))
print('Angulo entre A-C:',round(gradosac,2))


# Despues de ver el resultado podemos ver que por una diferencia considerable el producto B es mas cercano a A, ya que el angulo de diferencia
# es de menos de 2

Producto punto A-B: 50.46
Producto punto A-C: 26.5
Angulo entre A-B: 1.77
Angulo entre A-C: 47.23


---

### Ejercicio 3 — Normalización (10 pts)

Normaliza los tres vectores (`producto_A`, `producto_B`, `producto_C`) para obtener sus vectores unitarios. Verifica, imprimiendo el resultado, que la norma de cada vector normalizado sea 1.

In [5]:
# Tu código aquí

#Sacamos los vectores unitarios y los normalizamos
vunia = producto_A/norma
vunitb = producto_B/normb
vunitc = producto_C/normc
norma = np.linalg.norm(vunia)
normb = np.linalg.norm(vunitb)
normc = np.linalg.norm(vunitc)
print('Vector unitario A:',vunia, 'Normalizado:',norma)
print('Vector unitario B:',vunitb, 'Normalizado:', normb)
print('Vector unitario C:',vunitc, 'Normalizado:',normc)


Vector unitario A: [0.60409488 0.42957858 0.67121653] Normalizado: 1.0
Vector unitario B: [0.59021707 0.41315195 0.69350506] Normalizado: 1.0
Vector unitario C: [0.19090089 0.95450444 0.22908106] Normalizado: 1.0


## Parte 2 — Matrices: mezcla de insumos

Una fábrica de jugos combina dos insumos (concentrado de fruta y agua) en distintas proporciones para dos líneas de producto. La matriz `M` representa esas proporciones (filas = línea de producto, columnas = insumo), y `P` representa un ajuste de escala para una nueva presentación. Ejecuta la siguiente celda — **no la modifiques**.

In [6]:
M = np.array([[2, 1],
              [1, 3]])

P = np.array([[1.5, 0],
              [0, 2.0]])

print(M)
print(P)

[[2 1]
 [1 3]]
[[1.5 0. ]
 [0.  2. ]]


---

### Ejercicio 4 — Multiplicación matricial (15 pts)

1. Calcula `M * P` (elemento a elemento) y `M @ P` (multiplicación matricial). Los resultados son distintos — en un comentario o celda de texto, explica brevemente por qué.
2. Verifica que las formas sean compatibles: ¿cuál sería el resultado de `P @ M`? Calcúlalo y compáralo con `M @ P` — ¿da el mismo resultado?

In [7]:
# Tu código aquí

mp = M * P
mxp = M @ P
pxm = P @ M
print('M*P:',mp)
print('M@P:',mxp)
print('P@M:',pxm)

# Como podemos ver, al tener diferente tamaño estas matrices no son conmutativas
# Asi que si influye el orden en que se realiza la multiplicacion

M*P: [[3. 0.]
 [0. 6.]]
M@P: [[3.  2. ]
 [1.5 6. ]]
P@M: [[3.  1.5]
 [2.  6. ]]


---

### Ejercicio 5 — Determinante e inversa (15 pts)

1. Calcula el determinante de `M` con `np.linalg.det()`. Confirma que `M` sí tiene inversa (determinante distinto de 0).
2. Calcula la inversa de `M` con `np.linalg.inv()`.
3. Verifica tu resultado calculando `M @ M_inv` — debe dar (aproximadamente) la matriz identidad.

In [8]:
# Tu código aquí
detm = np.linalg.det(M)
print(detm)
# Como es 5 podemos decir que si tiene inversa

invm = np.linalg.inv(M)
print(invm)

mxm = M @ invm
print(mxm)

5.000000000000001
[[ 0.6 -0.2]
 [-0.2  0.4]]
[[ 1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00]]


---

### Ejercicio 6 — Sistema de ecuaciones (15 pts)

La fábrica necesita producir un lote que requiere en total 180 unidades de la línea 1 y 300 unidades de la línea 2, según las proporciones de `M`. Esto se representa como el sistema $Mx = b$, con:

```python
b = np.array([180, 300])
```

1. Resuelve el sistema con `np.linalg.solve()` para encontrar cuántas unidades de cada insumo (`x`) se necesitan.
2. Verifica tu solución multiplicando `M @ x` y confirmando que el resultado coincide con `b`.

In [9]:
b = np.array([180, 300])

# Tu código aquí

x = np.linalg.solve(M,b)
print(x)

mx = M @ x
print(mx)

[48. 84.]
[180. 300.]


---

### Ejercicio 7 — Síntesis: distancia y similitud (20 pts)

Retomando los tres productos de la Parte 1:

1. Calcula la **distancia euclidiana** entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`, usando la norma de la diferencia entre los vectores (`np.linalg.norm(a - b)`).
2. Calcula la **similitud coseno** entre los mismos pares — es el cociente que ya calculaste en el Ejercicio 2 antes de aplicar `arccos()`: $\frac{a \cdot b}{\|a\| \|b\|}$.
3. Con base en ambas métricas (distancia y similitud coseno), concluye en una cadena de texto impresa cuál producto (`B` o `C`) es más parecido a `producto_A`, y si ambas métricas coinciden en la misma conclusión.

In [10]:
# Tu código aquí
distab = np.linalg.norm(producto_A - producto_B)
distac = np.linalg.norm(producto_A - producto_C)
print('Distancia A-B:',round(distab,2))
print('Distancia A-C:',round(distac,2))

print('Similitud de Cos AB:',cosab)
print('Similitud de Cos AC:',cosac)

# Dada que la distancia A-B<A-C y que la similitud de coseno AB>AC
#Podemos definir que el producto B es el mas parecido a producto A

Distancia A-B: 0.71
Distancia A-C: 5.47
Similitud de Cos AB: 0.9995203969214979
Similitud de Cos AC: 0.6791199021706347


---

## Antes de entregar

- Verifica que el notebook completo corra de principio a fin sin errores (**Entorno de ejecución → Ejecutar todas**).
- Confirma que no usaste pandas ni scikit-learn.
- Comparte el notebook con permiso de **edición** para el docente.